#!/bin/sh

FILE="/etc/modprobe.d/dgpu.conf"

if grep -q -F "modeset=" "$FILE"; then
    if grep -q -F "modeset=0" "$FILE"; then
        echo "GPU: Compute"
    else
        echo "GPU: Hybrid"
    fi
else
    echo "GPU: Integrated"
fi
