#!/bin/sh

echo "Creating dgpu.conf"

touch dgpu.conf
echo "blacklist i2c_nvidia_gpu" >> dgpu.conf
echo "blacklist nouveau" >> dgpu.conf
echo "blacklist nvidia" >> dgpu.conf
echo "blacklist nvidia-drm" >> dgpu.conf
echo "blacklist nvidia-modeset" >> dgpu.conf
echo "alias i2c_nvidia_gpu off" >> dgpu.conf
echo "alias nouveau off" >> dgpu.conf
echo "alias nvidia off" >> dgpu.conf
echo "alias nvidia-drm off" >> dgpu.conf

sudo mv dgpu.conf /etc/modprobe.d/dgpu.conf

echo "Removing NVIDIA-specific env variables to prevent needing prime-run with iGPU"

sudo sed -i '/__EGL_VENDOR_LIBRARY_FILENAMES/d' /etc/environment
sudo sed -i '/VK_ICD_FILENAMES/d' /etc/environment
sudo sed -i '/DXVK_FILTER_DEVICE_NAME/d' /etc/environment
sudo sed -i '/VKD3D_FILTER_DEVICE_NAME/d' /etc/environment
sudo sed -i '/__GLX_VENDOR_LIBRARY_NAME/d' /etc/environment
sudo sed -i '/VDPAU_DRIVER/d' /etc/environment
sudo sed -i '/CUDA_VISIBLE_DEVICES/d' /etc/environment


echo "Reboot now. NVIDIA disabled."
