#!/bin/sh

echo "Creating dgpu.conf"

touch dgpu.conf
echo "blacklist i2c_nvidia_gpu" >> dgpu.conf
echo "blacklist nouveau" >> dgpu.conf
echo "alias i2c_nvidia_gpu off" >> dgpu.conf
echo "alias nouveau off" >> dgpu.conf
echo "options nvidia-drm modeset=0" >> dgpu.conf
echo 'options nvidia "NVreg_DynamicPowerManagement=0x02"' >> dgpu.conf

sudo mv dgpu.conf /etc/modprobe.d/dgpu.conf

echo "Reboot now. NVIDIA available for compute, but will tear in games."
